### ISSUE TITLE
Method parameter name(s) may conflict with the actual template variable name in FileRenderer

### ISSUE THREAD

**Issue by hdogan** [midorikocak/view#1]
https://github.com/midorikocak/view/blob/2709a0d2b32087d33ec2ba7b00c85f9b9ebb7358/src/FileRenderer.php#L20-L21

Suppose that I have `filename` key in data, since the `$data` array is extracted and forced to be overwritten, `$filename` variable may be overwritten by that `extract` call. I haven't tested yet, I may be wrong.

I've used function/closure scope before (not to leak variables in included file to global scope) to include dynamically generated filename, than pass the required variables (like filename and data array) to it without declaring their names, like that one (probably bad practice):

```php
$renderer = function (): string {
    extract(func_get_arg(1), EXTR_OVERWRITE); // 2nd parameter holds template data array
    ob_start();
    include func_get_arg(0); // 1st parameter holds filename to be included
    return ob_get_clean();
};

echo $renderer($filename, $data);
```
*Edit: Fixed shitty grammar & func_get_args() -> func_get_arg()*

**Comment by midorikocak** [comment]
Why would that be a bad practice?

**Comment by hdogan** [comment]
> Why would that be a bad practice?

I don't remember exactly but that might be one of the static analyzer or IDE was complaining about the procedure declaration/usage. It was probably related to parameter signature (anonymous function defined with no parameters but called with passing parameters).

As for *bad practice* part, some people (in my opinion; *software elitists*) might count this usage as a bad practice -- or it's just my skeptical approach.

**Comment by midorikocak** [comment]
Fixed. https://github.com/midorikocak/view/commit/aeb0c30ba0eee7e3aa32346c7d3f90d2efd04a2c

**Comment by hdogan** [comment]
I think it still leaks `filename` and `data` method variables to included view file (so I can directly access  `$filename` and `$data` variables untouched in view file - the anonymous function scope still holds those variables and included file uses that scope). But, it's a choice, you can let users to access them or not. (I don't tell it should not be).

But if I choose to use `filename` key in my template data, and since the rendering method extracts all my template data keys to variables and overwrites previously defined ones (if any), the actual `$filename` value becomes user passed template variable value. Than `include` call  uses that modified `$filename` variable. (This was the reason why I used func_get_arg(n) instead of named variable definition/parameter declaration before).

Quick example:

```php
$naughtyData = [
    'filename' => '/etc/passwd',
];

$renderer = new FileRenderer();
$view = new View($this->renderer);
$view->setTemplate('template.php');
echo $this->view->render($naughtyData);
```

PS #1: (Disclaimer) I couldn't test the code and all those ideas are just paranoiac theories, I'm still on 7.3 and too lazy to upgrade it to 7.4 *sigh*

PS #2: 🇹🇷 Ingilizce anlatmak ta ne dertmis yav, 30 dakikada duzelte duzelte anca dandik aciklama cikti...
